"""Add is_free to modules

Revision ID: 177e26b2ba68
Revises: 37860b8c5f31
Create Date: 2026-02-15 00:56:19.302515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '177e26b2ba68'
down_revision: Union[str, None] = '37860b8c5f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('modules', sa.Column('is_free', sa.Boolean(), nullable=False))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'is_free')
    # ### end Alembic commands ###
