"""Add xp to User model

Revision ID: 1b99617fd53c
Revises: 6fe6f076e867
Create Date: 2025-02-11 20:43:06.901992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b99617fd53c'
down_revision: Union[str, None] = '6fe6f076e867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('xp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'xp')
    # ### end Alembic commands ###
