"""Add prerequisites fieldto Tracks model

Revision ID: 5518b9a240f0
Revises: 3d6ed8f39776
Create Date: 2025-03-11 17:30:54.944150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5518b9a240f0'
down_revision: Union[str, None] = '3d6ed8f39776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('prerequisites', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'prerequisites')
    # ### end Alembic commands ###
