"""Update Track and Course to ensure Many to Many Relationship

Revision ID: 6f6271c7aaeb
Revises: 6ca9b928c375
Create Date: 2025-04-24 14:46:14.256926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f6271c7aaeb'
down_revision: Union[str, None] = '6ca9b928c375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_courses_track_id', table_name='courses')
    op.drop_constraint('courses_track_id_fkey', 'courses', type_='foreignkey')
    op.drop_column('courses', 'track_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('track_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('courses_track_id_fkey', 'courses', 'tracks', ['track_id'], ['id'])
    op.create_index('ix_courses_track_id', 'courses', ['track_id'], unique=False)
    # ### end Alembic commands ###
