"""Add unique constraint to order in Module and Lesson

Revision ID: 70dfca65115e
Revises: 6f6271c7aaeb
Create Date: 2025-04-28 12:17:32.483270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70dfca65115e'
down_revision: Union[str, None] = '6f6271c7aaeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_module_lesson_order', 'lessons', ['module_id', 'order'])
    op.create_unique_constraint('unique_course_module_order', 'modules', ['course_id', 'order'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_course_module_order', 'modules', type_='unique')
    op.drop_constraint('unique_module_lesson_order', 'lessons', type_='unique')
    # ### end Alembic commands ###
