"""Refactor database relationships using backref

Revision ID: 894c40fbe23c
Revises: 70dfca65115e
Create Date: 2025-05-02 12:45:47.737213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '894c40fbe23c'
down_revision: Union[str, None] = '70dfca65115e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
