"""Add action_url to notifications

Revision ID: 90a24ac2c38c
Revises: eb049b24a583
Create Date: 2026-03-03 12:32:40.951227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90a24ac2c38c'
down_revision: Union[str, None] = 'eb049b24a583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('action_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'action_url')
    # ### end Alembic commands ###
