"""Add completed at field to learning path model

Revision ID: c648af5c8d18
Revises: 5518b9a240f0
Create Date: 2025-03-12 14:38:22.522437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c648af5c8d18'
down_revision: Union[str, None] = '5518b9a240f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_paths', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_paths', 'completed_at')
    # ### end Alembic commands ###
